require("servers..keybind")
require("servers..bashls")
require("servers..cssls")
require("servers..gopls")
require("servers..html")
require("servers..luals")
require("servers..yamls")
require("servers..phpactor")
require("servers..pylsp")
require("servers..rust_analyzer")
require("servers..sqls")
require("servers..texlab")
require("servers..tsserver")
require("lspconfig").puppet.setup({})
require("config..mcp")
require("config..companion")
-- require("config..copilot")
require("servers..javals")
require("servers..kotlinls")
require("servers..solidity")
require("config..theme")
require("config..rest")
require("config..dart")
require("config..mini")
require("config..colors")
require("config..autotag")
require("config..evil_lualine")
require("config..dap")
require("config..noice")
require("config..dropbar")
require("dapui").setup()
require("config..telescope")
require("config..treesitter")
require("config..gitsign")
require("config..format")
require("colorizer").setup({
	"*", -- Highlight all files, but customize some others.
	css = { rgb_fn = true }, -- Enable parsing rgb(...) functions in css.
	html = { names = false },
})
require("which-key").setup({})
require("lspconfig").pyre.setup({})

vim.cmd([[ autocmd BufRead,BufNewFile *.org set filetype=org ]])
vim.cmd([[ autocmd BufRead,BufNewFile *.org set filetype=org ]])
vim.cmd([[
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent! loadview
]])
vim.lsp.inlay_hint.enable(true)
